import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How PrepNexa collects, uses, and protects your data — including resumes, interview answers, and AI processing.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-12">
      <h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">
        Privacy Policy
      </h1>
      <p className="mt-3 text-sm text-muted-foreground">
        Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
      </p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="mb-2 text-lg font-bold text-foreground">
            1. Information we collect
          </h2>
          <p>
            We collect the information you provide: your name, email address,
            interview answers, uploaded resumes, and interview results. We also
            collect basic analytics such as pages visited.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-bold text-foreground">
            2. How we use your data
          </h2>
          <p>
            Your data is used to run the service: authenticate you, generate AI
            mock interviews and feedback, analyze your resume, and track your
            usage for fair-use limits. AI feedback is generated by processing
            your resume text and interview answers.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-bold text-foreground">
            3. AI processing
          </h2>
          <p>
            Resume and interview content is sent to third-party AI providers to
            generate feedback. We do not use this content to train external
            models intentionally. AI-generated feedback is provided to you for
            practice and education — it is not a guarantee of any interview
            outcome.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-bold text-foreground">
            4. Resumes & uploads
          </h2>
          <p>
            Your uploaded resumes are stored privately in our database and are
            only accessible to you through your account. Resumes are processed
            server-side for analysis.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-bold text-foreground">
            5. Cookies & advertising
          </h2>
          <p>
            We use essential cookies for authentication and session management.
            Free accounts may see advertisements from third-party ad networks;
            Premium (Pro) accounts are ad-free. See our{" "}
            <a className="text-primary hover:underline" href="/cookie-policy">Cookie Policy</a>.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-bold text-foreground">
            6. Your rights
          </h2>
          <p>
            You can request access to, correction of, or deletion of your
            personal data by contacting us. You can also delete your account
            and data at any time.
          </p>
        </section>
        <section>
          <h2 className="mb-2 text-lg font-bold text-foreground">
            7. Contact
          </h2>
          <p>
            Questions about this policy? Reach us via the{" "}
            <a className="text-primary hover:underline" href="/contact">contact page</a>.
          </p>
        </section>
      </div>
    </div>
  );
}